version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  MorScout:
    logging:
      *default-logging
    image: mortorqrobotics/morscout:dev
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
    depends_on:
      - MongoDB
      - Consul
    expose:
      - 3000
      - 443
      - 8301
      - 8302
      - 8400
      - 8500
      - 8600
    networks:
      app:
        aliases:
          - morscout
      consul:
        # ipv4_address: 192.19.0.4

networks:
  app:
  consul:
    ipam:
      driver: default
      # config:
      #   - subnet: "192.19.0.0/24"
