container:
    image: node:lts-stretch

test_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[4d6a291143f26cb298cc95deae4bda9479e2696de6069f91159c876b4763d9fe39439f859c1b68fd198282db32c5e011]
    MONGOMS_SYSTEM_BINARY: /usr/bin/mongod
  container:
    matrix:
      #image: node:stretch
      image: node:dubnium-stretch
  install_script:
    - apt-get update
    - apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev mongodb-server
  yarn_install_script: yarn install
  test_script: yarn run test-coverage
  coverage_upload_script: bash <(curl -s https://codecov.io/bash) -F `node -v | sed 's/\..*$//'` -s coverage/ -t $CODECOV_TOKEN

lint_task:
  install_script:
    - apt-get update
    - apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  yarn_install_script: yarn install
  lint_script: yarn run lint

docker_builder:
  trigger_type: manual
  depends_on:
    - test
    - lint
  env:
    NODE_VERSION: 10.13.0
    ARCH: x64
    YARN_VERSION: 1.10.1
    DOCKER_USERNAME: eschabblowski
    DOCKER_PASSWORD: ENCRYPTED[5a6ab12ab304d3b0720848514f01fb37047b4ef50b8f4d805d9a696453a981b62e6e0c26f4359822503a9b26e5055b7f]
    SNYK_API_KEY: ENCRYPTED[314a3a0ecb95b127e5d8913af21829d6a5fe46ef7fc707f3a1c9fc1da8afe7740a3f956c42753b52007aaabbec707ad2]
  node_install_script:
    - set -x
    - curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz"
    - tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner
    - rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz"
    - ln -s /usr/local/bin/node /usr/local/bin/nodejs
  snyk_install_script: npm i -g snyk
  snyk_login_script: snyk auth $SNYK_API_KEY
  docker_login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  pull_script:
    - docker-compose pull --file docker/prod/docker-compose.yml
    - docker-compose pull --file docker/dev/docker-compose.yml
  docker_build_script:
    - docker-compose build --file docker/prod/docker-compose.yml
    - docker-compose build --file docker/dev/docker-compose.yml
  docker_bundle_script:
    - docker-compose bundle --file docker/prod/docker-compose.yml -o morscout.dab
  test_script: snyk test --docker $DOCKER_USERNAME/$CIRRUS_REPO_NAME:latest
  tag_script: docker tag $DOCKER_USERNAME/$CIRRUS_REPO_NAME:latest $DOCKER_USERNAME/$CIRRUS_REPO_NAME:r`echo $CIRRUS_TAG | sed "s/^[a-z0-9A-Z]//"`
  docker_push_script:
    - docker-compose push --file docker/prod/docker-compose.yml
    - docker-compose push --file docker/dev/docker-compose.yml
