FROM node:dubnium

LABEL dev="true"

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY yarn.lock yarn.lock
# Create SSL Certificates and install dependencies
RUN apt update && apt upgrade -y && apt install openssl -y && mkdir ssl\
    && openssl req -x509 -nodes -days 365 -newkey rsa:8192 -keyout ssl/server.key -out ssl/server.crt\
    -subj \
    "/C=US/ST=California/L=Los Angeles/O=MorTorq Robotics/OU=MorScout/CN=scout.morteam.com"\
    && yarn --non-interactive --silent --frozen-lockfile\
    && npm i -g nodemon

# Bundle app source
COPY . .

CMD [ "nodemon", "./server/docker.js", "--development" ]