version: '3.4'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  MorScout:
    image: eschabblowski/morscout:latest # change this
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8433:433"
    networks:
      app:
        aliases:
          - morscout
  db:
    image: mongo
    logging:
      *default-logging
    expose:
      - 27017
    networks: 
      app:
        aliases:
          - db
      backup:
        aliases:
          - db

networks:
  app:
  backup: