version: '3.6'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  nginx:
    build:
      context: ../nginx
      args:
        address: morteam.com
    networks:
      app:
       aliases:
        - load-balancer
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8433:433"
    depends_on:
      - Consul
  Consul:
    image: consul:latest
    networks:
      - app
      - backup
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: null
    command: consul agent -dns-port=53 -recursor=8.8.8.8 -bind=0.0.0.0
    expose:
      - 53
  Vault:
    image: vault:latest
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: "{\"backend\": {\"file\": {\"path\": \"/vault/file\"}}, \"default_lease_ttl\": \"168h\", \"max_lease_ttl\": \"720h\"}"
    command: server
    cap_add:
      - IPC_LOCK
    depends_on:
      - Consul
    networks:
      - app
      - backup
    expose:
      - 8200
  MorScout:
    image: morscout:latest
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    depends_on:
      - db
    expose:
      - 443
    networks:
      app:
        aliases:
          - morscout
  db:
    image: mvertes/alpine-mongo
    logging:
      *default-logging
    expose:
      - 27017
    networks:
      app:
        aliases:
          - db
      backup:
        aliases:
          - db

networks:
  app:
  backup:
