version: '3.6'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  MorScout:
    logging:
      *default-logging
    image: mortorqrobotics/morscout:latest
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    depends_on:
      # - MongoDB
      - Consul
    expose:
      - 443
      - 8301
      - 8302
      - 8400
      - 8500
      - 8600
    networks:
      app:
        aliases:
          - morscout
      consul:
        ipv4_address: 192.19.0.4
  nginx:
    extends:
      file: ../docker-common.yml
      service: nginx
    depends_on:
      - Consul
  Consul:
    extends:
      file: ../docker-common.yml
      service: Consul
    ports:
      - "127.0.0.1:8500:8500"
  Vault:
    extends:
      file: ../docker-common.yml
      service: Vault
    depends_on:
      - Consul
  MongoDB:
    extends:
      file: ../docker-common.yml
      service: MongoDB

networks:
  app:
  consul:
    ipam:
      driver: default
      config:
        - subnet: "192.19.0.0/24"
