# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'morscout' do
  pod 'AppCenter/Push', '~> 1.13.2'
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for morscout

  

  platform :ios, '9.0'
  target 'morscoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'morscout-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for morscout-tvOS

  target 'morscout-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
